### ISSUE TITLE
Página de evento no site do programa Mozilla Reps

### ISSUE THREAD

**Issue by mmsdocs** [GiovanniSM20/rust-roadshow-rj.rs#7]

**Comment by mmsdocs** [comment]
Cadastrar aqui: https://reps.mozilla.org/

**Comment by GiovanniSM20** [comment]
Nosso evento no Mozilla Reps : 

https://reps.mozilla.org/e/dive-into-rust-startgrid/ => Dia 1

https://reps.mozilla.org/e/dive-into-rust-startgrid-1/ => Dia 2
